[project]
name = "mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jolanta Hyla", email = "jhyla@student.agh.edu.pl" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.143.0",
    "httpx>=0.28.1",
    "httpx2>=2.13.1",
    "pre-commit>=4.6.2",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "pytest-dotenv>=0.5.2",
    "python-dotenv>=1.2.4",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
mlops = "mlops:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
